apiVersion: apps/v1
kind: Deployment
metadata:
  name:  PRODUCTION
  namespace: ms
  labels:
    app:  PRODUCTION
spec:
  selector:
    matchLabels:
      app: PRODUCTION
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  PRODUCTION
    spec:
      containers:
      - name:  PRODUCTION
        image:  PRODUCTION:latest
        ports:
        - containerPort:  3333
          name:  PRODUCTION

---
apiVersion: v1
kind: Service
metadata:
  name: PRODUCTION
  namespace: ms
spec:
  selector:
    app: PRODUCTION
  type: NodePort
  ports:
  - name: PRODUCTION
    port: 3333
    targetPort: 3333
   